import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Afacad } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs"
import { dark } from "@clerk/themes";

const afacad = Afacad({
  variable: "--font-afacad",
  subsets: ["latin"],
  // weight: ["400", "700"]
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const viewport: Viewport = {
  themeColor: '#2E2A1F',
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const localization = {
  signUp: {
    start: {
      title: "Join Spark 🔱 Bites",
      subtitle: 'And save your favorite recipes',
    },
  },
  signIn: {
    start: {
      title: "Welcome back to Spark 🔱 Bites",
      subtitle: "Sign in to continue cooking"
    }
  }
} as const;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider 
    appearance={{
      baseTheme: dark,
      cssLayerName: "clerk",
      variables: { colorPrimary: "#E6B800", colorRing: "#E6B800" },
      elements: { formField: { borderColor: "#E6B800" }}
    }} 
    localization={localization}>
      <html lang="en">
        <body
          className={`${afacad.className} ${afacad.variable} antialiased bg-background text-foreground`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
